spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: USER-SERVICE-APP
          uri: lb://USER-SERVICE-APP
          predicates:
            - Path=/api/users/**
        - id: QUIZ-SERVICE
          uri: lb://QUIZ-SERVICE
          predicates:
            - Path=/api/quizzes/**
        - id: QUESTIONS-SERVICE
          uri: lb://QUESTIONS-SERVICE
          predicates:
            - Path=/api/questions/**


server:
  port: 8083
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

